In [6]:
!pip install langchain langchain-community langchain-core

Requirement already satisfied: langchain in /usr/local/lib/python3.10/dist-packages (0.2.12)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.10/dist-packages (0.2.11)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.10/dist-packages (0.2.29)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (6.0.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.0.31)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (3.10.1)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (4.0.3)
Requirement already satisfied: langchain-text-splitters<0.3.0,>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (0.2.2)
Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in /usr/local/lib/python3.10/dist-packages (from langchain) (0.1.98)
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain) (1.26.4)
Requirement already satisfied: pydantic<3,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.8.2)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (8.5.0)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /usr/local/lib/python3.10/dist-packages (from langchain-community) (0.6.7)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.10/dist-packages (from langchain-core) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.10/dist-packages (from langchain-core) (24.1)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.10/dist-packages (from langchain-core) (4.12.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (2.3.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (24.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.9.4)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.10/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community) (3.21.3)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community) (0.9.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.10/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core) (3.0.0)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.17->langchain) (3.10.6)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain) (2.20.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2024.7.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.0.3)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community) (1.0.0)

In [7]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.10/dist-packages (1.40.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from openai) (0.27.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from openai) (0.5.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from openai) (2.8.2)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai) (4.66.5)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.10/dist-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (1.2.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (2024.7.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (2.20.1)

In [8]:
# Web Document Loader HTML 이나 javascript 코드 만 걷어내고 웹페이지를 그대로 Document객체로 덤프하는 역할
# 원하는 내용만을 가져올 수 없어서 butifulsoup에 비해 잘 사용되지 않음

from langchain.document_loaders import WebBaseLoader
loader = WebBaseLoader('https://zdnet.co.kr/view/?no=20240807161811')
data = loader.load()

print(data)
print(data[0].page_content)

[Document(metadata={'source': 'https://zdnet.co.kr/view/?no=20240807161811', 'title': '삼성·SK하이닉스, 9.4兆 보조금 받고 美 투자 속도 낸다 - ZDNet korea', 'description': '삼성전자에 이어 SK하이닉스도 미국 정부로부터 반도체 보조금 지원이 확정되면서 양사의 팹 건설에 속도가 붙을 전망이다. 두 회사가 미국 정부로부터 지원받는 직접 보조금은 모두 합쳐 한화로 약 9조4천억원(68억5천만 달러)에 달한다.삼성전자는 2022년부터 반도체 공장을 건설 중이며, SK...', 'language': 'ko'}, page_content='\n\n\n\n\n삼성·SK하이닉스, 9.4兆 보조금 받고 美 투자 속도 낸다 - ZDNet korea\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nZDNet Korea 뉴스레터 구독신청\n\n\n구독신청\n닫기\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nZDNet USA\nZDNet China\nZDNet Japan\n\n\nEnglish\n지디넷 웨비나\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n뉴스\n\n\n\n\n최신뉴스\n방송/통신\n컴퓨팅\n홈&모바일\n인터넷\n반도체/디스플레이\n\n\n카테크\n헬스케어\n게임\n중기&스타트업\n유통\n금융\n\n\n과학\n디지털경제\n인사•부음\n취업/채용\n인터뷰\n글로벌뉴스\n\n\n\n\n\n\n\n\n인공지능\n\n\n\n\n로봇\n\n\n\n\n반도체\n\n\n\n\n컨퍼런스\n\n\n\n\n칼럼•연재\n\n\n\n\n포토•영상\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n삼성·SK하이닉스, 9.4兆 보조금 받고 美 투자 속도 낸다\n[이슈진단+] 반도체 제조시설 美로 확대…국내 소부장에겐 희소식\n반도체ㆍ디스플레이입력 :2024/08/07 16:59\xa0\xa0\xa0\xa0수정: 2024/08/07 23:15\n\n\n\n\n\n\n이나리 기자\n기자 페이지 구독\n기자의 다른기사 보기\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n삼성전자에 이어 SK하이닉스도 미국 정부로부터 반도체 보조금 지원이 확정되면서 양사의 팹 건설에 속도가 붙을 전망이다. 두 회사가 미국 정부로부터 지원받는 직접 보조금은 모두 합쳐 한화로 약 9조4천억원(68억5천만 달러)에 달한다.\n삼성전자는 2022년부터 반도체 공장을 건설 중이며, SK하이닉스는 건설 착공을 앞두고 있다. 양사는\xa0건설 인프라 확보에 더욱 집중할 것으로 보인다. 또한\xa0양사의 반도체 생산시설 확대는 국내 소부장(소재, 부품, 장비) 업체들에게 글로벌 진출 기회가 될 것으로 기대된다.\n\n\n조 바이든 미국 대통령이 2022년 8월 9일 오전(미국 현지시간) 백악관에서 미국 반도체산업 지원법에 서명했다. (사진=미국 상무부)\n\n\n■ SK하이닉스, HBM 등 AI 메모리 패키징 시설 건설…4.5억 달러 보조금 확보\n\n미국 상무부는 지난 6일 SK하이닉스의 인디애나주 반도체 패키징 시설 투자에 4억5천만 달러(약 6천200억원)의 직접 보조금과 5억 달러의 대출 지원을 결정하면서 예비거래각서(PMT, Preliminary Memorandum of Terms)에 서명했다고 발표했다. 또 미국 재무부는 SK하이닉스가 투자하는 금액의 최대 25%까지 세제혜택을 제공할 예정이다.\n앞서 지난 4월 SK하이닉스는 인디애나주 웨스트라피엣에 38억7천만 달러(약 5조2천억원)를 투자해 인공지능(AI) 메모리용 어드밴스드 패키징 생산기지 및 연구개발(R&D) 시설을 건설한다고 발표했다. 이번 투자로 SK하이닉스는 약 1000개의 일자리를 창출하고, 퍼듀(Purdue) 대학 등 현지 연구기관과 반도체 연구·개발에 협력할 계획이다.\n\n\n표=지디넷코리아 박은주\n\nSK하이닉스는 오는 2028년까지 공장을 완공하고 같은해 하반기부터 차세대 고대역폭메모리(HBM) 등 AI 메모리를 생산한다는 계획이다.\nSK하이닉스의 인디애나 팹은 고객사인 엔비디아와 협력사인 대만 TSMC와 함께 삼각편대를 이뤄 시너지를 낼 것으로 보인다. SK하이닉스는 AI 반도체 1위인 엔비디아와 HBM3(4세대) 독점 공급 계약에 이어 HBM3E(5세대)도 최초 공급 계약을 맺는 활약으로 HBM 시장에서 독보적인 1위다. TSMC는 파운드리 시장에서 60% 이상 점유율로 1위이며, 고객사로 엔비디아를 확보하고 있다.\n\n■ 삼성전자, 2·4나노 파운드리 팹, 패키징 시설 투자…64억 달러 보조금 확보\n\n삼성전자는 지난 4월 미국 정부로부터 반도체 보조금으로 64억 달러(약 8조8505억원)의 지원금을 받기로 확정됐다.\xa0이는 미국 인텔(85억 달러), 대만 TSMC(66억 달러)에 이어 세번째로 많은 보조금 규모다.\xa0\n\n\n삼성전자가 미국 텍사스주 테일러시에 반도체 공장을 건설한다. (사진= 미국반도체산업협회(SIA) SNS)\n\n삼성전자는 반도체 보조금을 받게 되면서 텍사스주에 2022년부터 건설 중인 파운드리 1공장 외에도 추가로 2공장을 건설하고, 첨단 패키징 공장과 R&D 센터도 짓기로 결정했다. 이에 따라 삼성전자의 미국 투자액은 기존 170억 달러(약 23조4천억원)에서 400억 달러(약 55조3천억원)로 대폭 늘어났다. 파운드리 공장은 2026년부터 양산을 시작하며, 첨단 패키징 시설 및 R&D 센터 등은 2027년 가동할 계획이다.\n미국에는 애플, 엔비디아, AMD, 브로드컴 등 핵심 팹리스 기업이 다수 위치한다. 이점은 삼성전자와 TSMC가 고객사를 확보하기 위해 미국에 신규 파운드리 팹을 건설하기로 결정한 이유다. 무엇보다 미국 정부가 자국 내 반도체 공급망을 확보하기 위해 글로벌 기업에도 보조금을 지원한다는 점도 크게 적용한 것으로 보인다.\n\n■ 건설 인프라 확보 시급…미국 시장 진출 국내 소부장에게 호재\n\n삼성전자와 SK하이닉스는 반도체 보조금을 확보하게 되면서 투자금 부담을 덜었지만, 앞으로 시설투자 관련 인프라 확보와 인력 확충 등 해결해야 할 과제가 남아 있다.\n김양팽 산업연구원은 전문위원은 “당장은 반도체 제조 인력 보다는 반도체 공장 건설에 필요한 인력 확보가 관건”이라며 “최근 TSMC가 미국 시설 투자에서 현지 전문 인력 부족 문제로 건설 일정이 늦어진 것처럼 숙련된 건설 인력을 확보하는 것이 중요하다”고 말했다. 이어 그는 “공장이 가동되는 시점에는 제조 인력 확보에도 힘써야 할 것”이라고 덧붙였다.\n실제로 지난해 TSMC는 숙련된 건설 인력 부족으로 애리조나 1공장과 2공장의 가동시기를 각각 1~2년씩 늦춘 바 있다.\n미국을 비롯한 전세계 반도체 생산시설 확대는 국내 소부장\xa0업체들에게는 기회가 될 것으로 기대된다.\n박재근 한양대학교 융합전자공학부 교수는 “삼성전자와 SK하이닉스의 미국 진출은 국내 소부장 업체들에게 희소식”이라며 “두 회사가 미국에 공장을 건설하면 글로벌 장비 외에도 기존에 사용하던 한국 업체의 장비도 사용할 가능성이 있다”고 말했다.\n\n관련기사\n\n\n美 정부, SK하이닉스 인디애나 공장에 6200억 보조금 지급2024.08.06\n美 정부, 앰코 \'패키징 공장\'에 반도체 보조금 4억 달러 지급2024.07.28\n반도체, 설비 증설이 경쟁력…"보조금 늘려야 韓 시장 입지 사수"2024.06.13\n美, 마이크론에 반도체 보조금 8.3조원 지급..."메모리 주도권 되찾자"2024.04.26\n\n\n김양팽 전문위원은 “국내 반도체 소부장 업체 중에는 자신의 기술로 해외 고객사를 뚫을 만한 역량있는 기업이 몇개 되지 않는다”며 “이들이 삼성과 SK를 따라 해외에 진출하면, 경쟁력을 키워 다른 고객사를 확보할 수 있다”고 설명했다.\n한편 삼성전자와 SK하이닉스가 미국 정부로부터 받는 반도체 보조금은 미국 반도체산업지원법(칩스법)의 일환이다. 2022년 제정된 반도체법은 미국 내 반도체 투자를 장려하기 위해 5년간 생산 보조금(390억 달러)과 연구개발(R&D) 지원금(132억 달러) 등 총 527억달러(75조5천억원)를 지원하는 내용이다. 이를 통해 미국은 2030년까지 전 세계 최첨단 반도체 생산량의 20% 차지하는 것을\xa0목표로 한다.\n\n\n\n\n\n\n\n\n이나리 기자narilee@zdnet.co.kr\n기자의 다른 기사 보기 \n\n\n\n\n\n\n\n\n\n\n\n\n\n삼성전자\n반도체\nSK하이닉스\n보조금\nTSMC\n미국\n소부장\nHBM\n파운드리\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n라이브리 댓글 작성을 위해 javascript를 활성화해 주세요\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n지금 뜨는 기사\n\n\n\n\n\n\n\n\n\n\n\n이시각 헤드라인\n\n\n\n\n\n\n\n\n삼성·SK하이닉스, 9.4兆 보조금 받고 美 투자 속도 낸다\n\n\n\n\n\n\n\n\n\n\n\n"전동 휠체어 타고 패럴림픽 가요...사람에 꼭 필요한 기술 공급할 것"\n\n\n\n\n\n\n\n\n\n\n\n[현장] 싱가포르 은행, LG유플러스도 푹 빠졌다...클라우데라 찾는 기업들, 왜?\n\n\n\n\n\n\n\n\n\n\n\n두산, \'밥캣-로보틱스\' 합병비율 변경없이 간다…"M&A 추진할 것"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nZDNet Power Center\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nConnect with us\n\n\n\n\n\n\n\n                \t© 2020 ZDNET, A RED VENTURES COMPANY. ALL RIGHTS RESERVED. Global family site >>\xa0\xa0CNET.com | ZDNet.com\n\n\n\n\nZDNet Korea Newsletter 구독 신청\n\n구독신청\n\n\n\n\n\n회사소개\n광고문의\nDB마케팅문의\n제휴문의\n개인정보처리방침\n이용약관\n청소년 보호정책\n\n\n회사명 : (주)메가뉴스\n제호 : 지디넷코리아\n등록번호 : 서울아00665\n\n\n등록연월일 : 2008년 9월 23일\n사업자 등록번호 : 220-87-44355\n\n\n주소 : 서울시 마포구 양화로111 지은빌딩 3층\n대표전화 : (02)330-0100\n\n\n발행인 : 김경묵\n편집국장 : 김태진\n개인정보보호 책임자·청소년보호책임자 : 김익현\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')]





삼성·SK하이닉스, 9.4兆 보조금 받고 美 투자 속도 낸다 - ZDNet korea


















































































ZDNet Korea 뉴스레터 구독신청


구독신청
닫기
































ZDNet USA
ZDNet China
ZDNet Japan


English
지디넷 웨비나









































뉴스




최신뉴스
방송/통신
컴퓨팅
홈&모바일
인터넷
반도체/디스플레이


카테크
헬스케어
게임
중기&스타트업
유통
금융


과학
디지털경제
인사•부음
취업/채용
인터뷰
글로벌뉴스








인공지능




로봇




반도체




컨퍼런스




칼럼•연재




포토•영상

































삼성·SK하이닉스, 9.4兆 보조금 받고 美 투자 속도 낸다
[이슈진단+] 반도체 제조시설 美로 확대…국내 소부장에겐 희소식
반도체ㆍ디스플레이입력 :2024/08/07 16:59    수정: 2024/08/07 23:15






이나리 기자
기자 페이지 구독
기자의 다른기사 보기
























삼성전자에 이어 SK하이닉스도 미국 정부로부터 반도체 보조금 지원이 확정되면서 양사의 팹 건설에 속도가 붙을 전망이다. 두 회사가 미국 정부로부터 지원받는 직접 보조금은 모두 합쳐 한화로 약 9조4천억원(68억5천만 달러)에 달한다.
삼성전자는 2022년부터 반도체 공장을 건설 중이며, SK하이닉스는 건설 착공을 앞두고 있다. 양사는 건설 인프라 확보에 더욱 집중할 것으로 보인다. 또한 양사의 반도체 생산시설 확대는 국내 소부장(소재, 부품, 장비) 업체들에게 글로벌 진출 기회가 될 것으로 기대된다.


조 바이든 미국 대통령이 2022년 8월 9일 오전(미국 현지시간) 백악관에서 미국 반도체산업 지원법에 서명했다. (사진=미국 상무부)


■ SK하이닉스, HBM 등 AI 메모리 패키징 시설 건설…4.5억 달러 보조금 확보

미국 상무부는 지난 6일 SK하이닉스의 인디애나주 반도체 패키징 시설 투자에 4억5천만 달러(약 6천200억원)의 직접 보조금과 5억 달러의 대출 지원을 결정하면서 예비거래각서(PMT, Preliminary Memorandum of Terms)에 서명했다고 발표했다. 또 미국 재무부는 SK하이닉스가 투자하는 금액의 최대 25%까지 세제혜택을 제공할 예정이다.
앞서 지난 4월 SK하이닉스는 인디애나주 웨스트라피엣에 38억7천만 달러(약 5조2천억원)를 투자해 인공지능(AI) 메모리용 어드밴스드 패키징 생산기지 및 연구개발(R&D) 시설을 건설한다고 발표했다. 이번 투자로 SK하이닉스는 약 1000개의 일자리를 창출하고, 퍼듀(Purdue) 대학 등 현지 연구기관과 반도체 연구·개발에 협력할 계획이다.


표=지디넷코리아 박은주

SK하이닉스는 오는 2028년까지 공장을 완공하고 같은해 하반기부터 차세대 고대역폭메모리(HBM) 등 AI 메모리를 생산한다는 계획이다.
SK하이닉스의 인디애나 팹은 고객사인 엔비디아와 협력사인 대만 TSMC와 함께 삼각편대를 이뤄 시너지를 낼 것으로 보인다. SK하이닉스는 AI 반도체 1위인 엔비디아와 HBM3(4세대) 독점 공급 계약에 이어 HBM3E(5세대)도 최초 공급 계약을 맺는 활약으로 HBM 시장에서 독보적인 1위다. TSMC는 파운드리 시장에서 60% 이상 점유율로 1위이며, 고객사로 엔비디아를 확보하고 있다.

■ 삼성전자, 2·4나노 파운드리 팹, 패키징 시설 투자…64억 달러 보조금 확보

삼성전자는 지난 4월 미국 정부로부터 반도체 보조금으로 64억 달러(약 8조8505억원)의 지원금을 받기로 확정됐다. 이는 미국 인텔(85억 달러), 대만 TSMC(66억 달러)에 이어 세번째로 많은 보조금 규모다.


삼성전자가 미국 텍사스주 테일러시에 반도체 공장을 건설한다. (사진= 미국반도체산업협회(SIA) SNS)

삼성전자는 반도체 보조금을 받게 되면서 텍사스주에 2022년부터 건설 중인 파운드리 1공장 외에도 추가로 2공장을 건설하고, 첨단 패키징 공장과 R&D 센터도 짓기로 결정했다. 이에 따라 삼성전자의 미국 투자액은 기존 170억 달러(약 23조4천억원)에서 400억 달러(약 55조3천억원)로 대폭 늘어났다. 파운드리 공장은 2026년부터 양산을 시작하며, 첨단 패키징 시설 및 R&D 센터 등은 2027년 가동할 계획이다.
미국에는 애플, 엔비디아, AMD, 브로드컴 등 핵심 팹리스 기업이 다수 위치한다. 이점은 삼성전자와 TSMC가 고객사를 확보하기 위해 미국에 신규 파운드리 팹을 건설하기로 결정한 이유다. 무엇보다 미국 정부가 자국 내 반도체 공급망을 확보하기 위해 글로벌 기업에도 보조금을 지원한다는 점도 크게 적용한 것으로 보인다.

■ 건설 인프라 확보 시급…미국 시장 진출 국내 소부장에게 호재

삼성전자와 SK하이닉스는 반도체 보조금을 확보하게 되면서 투자금 부담을 덜었지만, 앞으로 시설투자 관련 인프라 확보와 인력 확충 등 해결해야 할 과제가 남아 있다.
김양팽 산업연구원은 전문위원은 “당장은 반도체 제조 인력 보다는 반도체 공장 건설에 필요한 인력 확보가 관건”이라며 “최근 TSMC가 미국 시설 투자에서 현지 전문 인력 부족 문제로 건설 일정이 늦어진 것처럼 숙련된 건설 인력을 확보하는 것이 중요하다”고 말했다. 이어 그는 “공장이 가동되는 시점에는 제조 인력 확보에도 힘써야 할 것”이라고 덧붙였다.
실제로 지난해 TSMC는 숙련된 건설 인력 부족으로 애리조나 1공장과 2공장의 가동시기를 각각 1~2년씩 늦춘 바 있다.
미국을 비롯한 전세계 반도체 생산시설 확대는 국내 소부장 업체들에게는 기회가 될 것으로 기대된다.
박재근 한양대학교 융합전자공학부 교수는 “삼성전자와 SK하이닉스의 미국 진출은 국내 소부장 업체들에게 희소식”이라며 “두 회사가 미국에 공장을 건설하면 글로벌 장비 외에도 기존에 사용하던 한국 업체의 장비도 사용할 가능성이 있다”고 말했다.

관련기사


美 정부, SK하이닉스 인디애나 공장에 6200억 보조금 지급2024.08.06
美 정부, 앰코 '패키징 공장'에 반도체 보조금 4억 달러 지급2024.07.28
반도체, 설비 증설이 경쟁력…"보조금 늘려야 韓 시장 입지 사수"2024.06.13
美, 마이크론에 반도체 보조금 8.3조원 지급..."메모리 주도권 되찾자"2024.04.26


김양팽 전문위원은 “국내 반도체 소부장 업체 중에는 자신의 기술로 해외 고객사를 뚫을 만한 역량있는 기업이 몇개 되지 않는다”며 “이들이 삼성과 SK를 따라 해외에 진출하면, 경쟁력을 키워 다른 고객사를 확보할 수 있다”고 설명했다.
한편 삼성전자와 SK하이닉스가 미국 정부로부터 받는 반도체 보조금은 미국 반도체산업지원법(칩스법)의 일환이다. 2022년 제정된 반도체법은 미국 내 반도체 투자를 장려하기 위해 5년간 생산 보조금(390억 달러)과 연구개발(R&D) 지원금(132억 달러) 등 총 527억달러(75조5천억원)를 지원하는 내용이다. 이를 통해 미국은 2030년까지 전 세계 최첨단 반도체 생산량의 20% 차지하는 것을 목표로 한다.








이나리 기자narilee@zdnet.co.kr
기자의 다른 기사 보기













삼성전자
반도체
SK하이닉스
보조금
TSMC
미국
소부장
HBM
파운드리














라이브리 댓글 작성을 위해 javascript를 활성화해 주세요














지금 뜨는 기사











이시각 헤드라인








삼성·SK하이닉스, 9.4兆 보조금 받고 美 투자 속도 낸다











"전동 휠체어 타고 패럴림픽 가요...사람에 꼭 필요한 기술 공급할 것"











[현장] 싱가포르 은행, LG유플러스도 푹 빠졌다...클라우데라 찾는 기업들, 왜?











두산, '밥캣-로보틱스' 합병비율 변경없이 간다…"M&A 추진할 것"































ZDNet Power Center



























































































Connect with us







                	© 2020 ZDNET, A RED VENTURES COMPANY. ALL RIGHTS RESERVED. Global family site >>  CNET.com | ZDNet.com




ZDNet Korea Newsletter 구독 신청

구독신청





회사소개
광고문의
DB마케팅문의
제휴문의
개인정보처리방침
이용약관
청소년 보호정책


회사명 : (주)메가뉴스
제호 : 지디넷코리아
등록번호 : 서울아00665


등록연월일 : 2008년 9월 23일
사업자 등록번호 : 220-87-44355


주소 : 서울시 마포구 양화로111 지은빌딩 3층
대표전화 : (02)330-0100


발행인 : 김경묵
편집국장 : 김태진
개인정보보호 책임자·청소년보호책임자 : 김익현

In [12]:
!pip install pypdf docx2txt

Requirement already satisfied: pypdf in /usr/local/lib/python3.10/dist-packages (4.3.1)
Collecting docx2txt
  Downloading docx2txt-0.8.tar.gz (2.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: typing_extensions>=4.0 in /usr/local/lib/python3.10/dist-packages (from pypdf) (4.12.2)
Building wheels for collected packages: docx2txt
  Building wheel for docx2txt (setup.py) ... done
  Created wheel for docx2txt: filename=docx2txt-0.8-py3-none-any.whl size=3959 sha256=0a3c0c5e9b22720c6143541f862f17ed9a381732026ccf416ea51644e8fdf49b
  Stored in directory: /root/.cache/pip/wheels/22/58/cf/093d0a6c3ecfdfc5f6ddd5524043b88e59a9a199cb02352966
Successfully built docx2txt
Installing collected packages: docx2txt
Successfully installed docx2txt-0.8

In [11]:
# Pdf 를 읽어서 Document 객체로 반환
from langchain.document_loaders import PyPDFLoader

loader = PyPDFLoader('/content/DJI_Osmo_Pocket_3_User_Manual_v1.0_en.pdf')
data = loader.load()
print(data[0].page_content)
print(data[0]) # pdf를 참고한 gpt의 답변에서 metadata 에 해당 pdf 페이지를 알 수 있어서 유용하게 사용됨

2023.10 v1.0User Manual
page_content='2023.10 v1.0User Manual' metadata={'source': '/content/DJI_Osmo_Pocket_3_User_Manual_v1.0_en.pdf', 'page': 0}

In [15]:
# [워드]docx 파일을 Document 형태로 파싱
from langchain.document_loaders import Docx2txtLoader

loader = Docx2txtLoader('/content/LLM이 만들어 내는 혁명과 교통산업.docx')
data = loader.load()
print(data)
print(data[0]) # 마지막 줄에 metadata가 출력되어 있어, 어떤 문서에서 가져왔는지 알 수 있다.

[Document(metadata={'source': '/content/LLM이 만들어 내는 혁명과 교통산업.docx'}, page_content="LLM이 만들어 내는 혁명과 교통산업\n\n김영욱\n\nMicrosoft에서 플랫폼 사업부에서 수석으로 일했으며 지금은 AI 전문기업인 Hello AI 창업해서 인공지능과 관련한 프로젝트 및 과제를 수행하고 있으며 강연과 집필 그리고 교육에도 힘쓰고 있다. \n\n\n\n 최근 모든 분야에서 이전에 없었던 급격한 기술 발전이 사회의 모습을 바꾸고 또 바뀐 사회 필요를 또 다시 새로운 기술로 채워 나가는 빠른 순환이 일어 나고 있다. 그런데 변화를 주도하는 기술 중에서 특히 IT 기술은 더더욱 그런 현상을 가속화 시킬 뿐만 아니라 주도하고 있는 현상을 우리는 쉽게 볼 수 있다. \n\n코로나 이후 전 세계적으로 어려운 경제 상황을 보여주고 있지만 상대적으로 유럽은 더더욱 큰 경제 불황의 고리에 빠져들고 있는데 유럽 경제가 힘든 이유는 우크라이나 전쟁을 비롯, 에너지 문제를 포함해서 여러 이유를 함께 생각해 볼 수 있지만 IT산업이 제대로 발전하지 못한 이유도 크게 한 몫하고 있다. 우리가 주변에서 편하게 사용하는 다양한 인터넷 서비스들 중 유럽 것을 찾아보기 힘든 것만 봐도 유럽은 여전히 전통적인 산업에 머물러 있다는 것을 알 수 있다. 또 미국의 S&P 500의 시가 총액 상위 종목들을 보면 애플, Microsoft, 구글, 아마존 그리고 테슬라 등 IT 관련 기술주가 상위권을 휩쓸고 있는 것을 볼 수 있다. 그렇게 우리는 IT 기술이 곧 경쟁력인 세상의 한복판에 살아가고 있다. \n\n\n\nThe age of Generative AI \n\n 작년 말 갑자기 등장한 ChatGPT는 최근 모든 이슈를 가져와도 비교가 되지 않을 만큼 큰 이슈를 일으키고 있다. 사람들은 ChatGPT를 보자마자 IT 역사에 큰 변화를 일으킬 또 하나의 마일스톤이 시작되었다는 생각 보다는 각자 필요한 용도로 활용 할 수 있다는 점에 열광하기 시작했다. 100만 사용자가 단 5일만에 가입한 사실만 보더라도 사람들이 얼마나 ChatGPT에 열광하고 있는 것을 알 수 있다.  \n\n <그림1> 주요 서비스의 회원 100만명 달성 시간 (출처: statista)\n\n ChatGPT 이전에 세상에서 이슈 몰이를 했던 인공지능으로는 구글의 알파고를 빼놓고 이야기 할 수 없다. 알파고는 바둑을 혹은 바둑만 전문적으로 추론 할 수 있는 인공지능이었다. 최근 알파고 이야기를 주변에서 찾아 볼 수 없는 이유는 알파고를 바둑 이외의 영역에 적용했을 때 인상적인 결과를 만들지 못했기 때문일지도 모른다. 항상 이런 전문성이라는 것은 양날의 검과 같아서 장점과 치명적인 한계를 함께 동반하는 것이 일반적이다. 비슷하게 우리 주변의 인공지능 시스템들은 대부분은 한정된 영역의 일만 할 수 있는 소위 말하는 전문가 시스템이었다. 집안의 온도를 맞추어 주고 공장의 품질 관리를 해주고 농장의 작물들을 키워주는 인공지능 시스템들도 모두 특정 용도에 최적화된 전문가 시스템이라고 할 수 있다. \n\n하지만 사람들이 인공지능에 거는 기대치는 이보다 훨씬 높다. 우리가 아이언맨 등의 영화에서 봤던 자비스와 같은 인공지능은 어떨까? 주인공인 토니 스타크가 묻는 질문에 적절하게 대답해주고 주변에 있는 시설들을 제어하면서 주인공의 또 하나의 동료로 완전히 함께 일하는 모습을 볼 수 있다. 사실 자비스와 같이 다양한 용도로 사용 할 수 있는 수준의 인공지능을 인공 일반 지능(AGI: Artificial General Intelligence) 기술이라고 말한다. 인공 일반 지능은 전문가 시스템에 반대되는 개념으로 사람들의 말과 말속의 맥락을 정확하게 이해하고 거기에 맞게 동작하거나 답을 해주는 것이 목표이다. ChatGPT는 이제까지 나왔던 그 어떤 인공 지능 기술 보다도 인공 일반 지능에 가장 가까운 기술이었고 그래서 사람들은 ChatGPT를 보면서 자비스를 떠올리고 있었는지도 모르겠다. \n\n\n\n전 세계의 말들을 학습한 LLM\n\n이전에는 컴퓨터에게 사람의 말을 가르치기 위해서 문법적인 접근을 했다. 언어들의 문법적인 원리를 연구하고 발견된 원리들을 컴퓨터에 소프트웨어로 제작하는 방식으로 접근을 했지만 의미 있는 결과를 도출하는 것이 어려웠다. 문법적인 접근이 어려움을 겪었던 이유는 모든 사람들이 문법적으로 이야기 하지 않는다는 점이 첫 번째 문제였다. 문법이라는 것이 일정한 듯 하면서도 모든 언어적인 현상들을 모두 문법으로 설명할 수 없었다. 또 다른 이유는 사람들은 계속해서 새로운 단어들을 만들어 내고 있다는 점이다. 단적인 예를 들자면 ‘구글링’이라는 단어는 구글이 등장하기 전에는 존재하지 않았던 동사였다. 그래서 문법적인 접근으로는 한계가 있음을 인정하지 않을 수 없었다. 문법적인 접근을 하는 대신 사람들이 실제 사용하는 말을 긁어 모아서 단어 사이의 가중치를 매기는 방식으로 접근하기 시작했다. 이 방식의 경우 사람들의 말의 양을 늘리면 늘릴 수록 결과물도 함께 좋아지는 장점이 있었고 또 인터넷 등에서 사람들이 실제로 사용하는 말을 모아서 학습하다 보니 새로운 단어들과 기존에 알려진 문법과 상관없는 현상들을 모두 분석할 수 있는 장점이 있었다. 문제는 말의 양을 늘리면 늘릴 수록 분석하는데 들어가는 컴퓨팅 비용도 기하급수적으로 늘어난다는 점에 있었다. 그래서 무한정으로 학습량을 늘리는 것은 어려웠다. 어찌되었든 이렇게 사람의 말을 학습해 놓은 것을 언어 모델(LM: Language Model)이라 부르는데 이 중에서도 특히 언어 모델을 엄청난 크기로 만들어 놓은 것을 거대 언어 모델(LLM: Large Language Model)이라고 불렀다. \n\n\n\n데이터세트\n\n토큰\n\n교육 비율\n\n일반 크롤링\n\n4100억개\n\n60%\n\n웹텍스트 2\n\n190억개\n\n22%\n\n책1\n\n120억개\n\n8%\n\n책2\n\n550억개\n\n8%\n\n위키백과\n\n30억개\n\n3%\n\n <표1> 대표적인 LLM인 GPT3의 학습에 사용된 데이터 양\n\n거대 언어 모델을 만드는 데에는 엄청난 비용과 컴퓨팅 인프라가 필요한 까닭에 주요 소프트웨어 회사에서 개발하고 있다. 최근에는 주로 구글, Microsoft, 엔비디아, 그리고 오픈AI와 같은 글로벌 대형 업체들이 주도적으로 연구와 개발을 하고 있는데 이중에서도 오픈AI는 상대적으로 작은 규모의 회사이긴 하지만 Microsoft가 14조가 넘는 비용을 투자하면서 선두로 나서게 되었으며 언어 모델인 GPT, 이미지를 생성하는 DALL-E2 이외에도 많은 연구를 하고 있다. \n\n\n\n지식전이 현상의 발견 \n\n거대 언어 모델을 만드는 과정에서 수 많은 말들을 처리하다 보니 잘 만들어진 언어 모델은 그 자체로 많은 잠재성을 가질 수 있게 되었다. 언어 모델에 들어 있는 말들 자체가 하나의 거대한 지식 체계로 동작하면서 새로운 능력들이 발현하게 되었는데 이와 같은 현상을 지식의 전이(Knowledge Transfer)라 부르게 되었다. 실제로 오픈AI가 만든 GPT-3 모델의 경우 기본적으로 감정의 분석, 문서의 요약, 번역, 질의응답, 작문, 문장의 재구성 등 많은 능력을 가지고 있어서 이미 많은 분야에서 이 능력을 활용하고 있거나 활용하기 위해서 시도하고 있다. GPT-4의 경우 이 보다 훨씬 더 큰 잠재력이 있는 것으로 알려져 있다. 지식의 전이 현상으로 인해 다양한 일들을 척척 해내는 것을 보면 거대 언어 모델의 능력이 무한 할 것 같지만 ChatGPT 역시 만능은 아니다. ChatGPT가 나름 다양한 능력을 가지고 있고 이전에 없었던 새로운 일들을 가능하게 해주는 놀라운 존재이긴 하지만 한계도 역시 분명하다. ChatGPT는 다음과 같이 알려진 한계가 있다. \n\n\n\n2021년 9월에 멈춘 학습\n\n일관성 없는 결과물\n\n거짓 정보 (Hallucination)\n\n영어에 비해 떨어지는 한국어 결과물\n\n\n\nChatGPT를 학습 시킬 때 전세계의 인터넷과 책에 있는 자료들을 긁어 모아서 학습을 시켰지만 그 학습 자료는 2021년 9월에 머물러 있다. 따라서 최신 정보를 묻는다면 대답을 할 수 없다. 가령 예를 들자면 \n\n\n\n‘지금 한국의 대통령은?’, \n\n‘오늘 삼성전자 주가는 얼마야?’,\n\n’내일 비가 올 것 같아?’\n\n\n\n이런 질문들에 대해서는 답변을 할 수 없다. 또 ChatGPT 자체는 학습된 데이터를 기반으로 말을 생성해 내는 것이 주된 기능이고 생성된 말의 일관성이나 혹은 사실 여부를 검증해 주지는 않는다. 그래서 질문 할 때 마다 다른 말을 만들어 내주는가 하면 또 때로는 아주 아주 진지하고 그럴싸한 거짓말을 하기도 한다. 모르는 사람들은 ChatGPT가 만들어내는 거짓말을 그대로 믿을 만큼 거짓말을 잘한다. 또 다른 문제로는 GPT-4에 이르러서는 조금 나아지긴 했지만 기본적으로 한국어 보다는 영어의 학습량이 많기 때문에 한국어 보다는 영어가 더 좋은 결과물을 보여주기도 한다. \n\n\n\n생성형 인공지능의 시대가 왔다. \n\n위에서 ChatGPT의 한계를 이야기 했지만 업계에서는 빠르게 한계를 극복하면서 빠르게 생성형 인공지능을 제품이나 서비스로 연결하고 있다. 생성형 인공지능과 관련해서는 구글, 메타, 엔비디아 그리고 국내의 네이버 등도 빠르게 움직이고 결과물을 내놓고 있지만 최근 이 분야에서 가장 빠르게 움직이고 있는 기업은 바로 Microsoft이다. \n\n Microsoft는 검색엔진인 빙(Bing)에 생성형 AI 기술을 적용해서 대화형으로 문제를 해결할 수 있는 방법을 제공하면서 빠르게 구글의 점유율을 가져오고 있다. 또 빙 이미지 크리에이터를 통해서 사용자들에게 필요한 이미지를 생성 할 수 있는 방법도 함께 제공하고 있다. \n\n Microsoft의 전략에서 특히 눈의 띄는 부분은 바로 플랫폼이다. Microsoft는 거대 언어 모델을 그 자체로 사용하지 않고 개발을 위한 시멘틱 커널 프레임웍(Semantic Kernel Framework)을 먼저 만들고 그 기반으로 코파일럿(Copilot)라는 이름으로 플랫폼화를 했다. 플랫폼화가 잘되고 나면 안정적으로 새로운 많은 제품과 서비스에서 거대 언어 모델의 효과를 즉시 발휘할 수 있게 확장 할 수 있게 된다. \n\n Microsoft는 Copilot 서비스를 소프트웨어 개발 도구로 활용할 수 있게 Github Copilot으로 출시해서 소프트웨어 개발 분야에서 활용 하는가 하면 일반인들을 위해서 윈도우 11에서 거대 언어 모델을 사용할 수 있는 Windows Copilot의 오픈 베타 버전을 내놓았다. \n\n\n<그림2> Windows Copilot (출처: Windows 11 Copilot 테스트 받은 편지함, ChatGPT 및 Bing AI 플러그인 통합 - GAMINGDEPUTY KOREA)\n\n 뿐만 아니라 워드, 엑셀, 파워포인트, 팀즈, 아웃룩 등 오피스 제품들을 클라우드 기반으로 제공하는 Microsoft 365에도 역시 코파일럿 제품이 들어가면서 이제 부터는 문서 작성이나 엑셀에서 데이터 분석, 발표용 슬라이드 작성등 대부분의 작업을 이제부터는 코파일럿과의 채팅을 통해서 해결할 수 있는 시대가 왔다. \n\n Microsoft 뿐만 아니다. 포토샵으로 유명한 어도비(Adobe)도 적극적으로 생성형 인공지능을 활용하고 있다. 포토샵에서 여러 도구들을 사용해서 사람이 이미지를 일일이 수정하는 것이 아니라 생성형 인공지능을 사용해서 영역을 지정하고 어떻게 수정할 것인지 말로 표현하면 인공지능이 이미지를 수정해주는 식으로 동작 할 수 있다. \n\n\n\n<그림3> 포토샵에서 생성형 인공지능의 활용(Photoshop Has Become a Lot More Powerful Thanks to Brand New Generative AI Features Using Adobe's Firefly (wccftech.com)\n\n이렇게 생성형 인공지능 기술들은 IT 산업 전반에서 IT와 사람 사이의 인터페이스를 변화 시키고 있다. 버튼을 누르거나 사용자의 입력에 의해서 반응하던 시스템이 아니라 사람과의 대화를 통해서 내용을 이용하고 함께 작업에 동참하는 자비스가 어느덧 이제는 우리 곁으로 들어왔다. \n\n\n\n교통산업과 거대 언어 모델 \n\n미국 최대 자동차 회사인 제너럴모터스(GM)이 ChatGPT를 자사 차량에 적용하는 방안을 모색하고 있다는 발표를 했다. 이런 변화가 자연스럽게 느껴지는 것은 자동차라는 공간이 단순한 이동 수단을 넘어서서 이제는 하나의 스마트 디바이스로 진화하고 있기 때문이다. 고성능 컴퓨터가 탑재되어서 완벽하지는 않아도 운전 보조 장치로는 충분한 수준의 자율주행을 수행할 수 있게 되었고 음성으로 대화가 가능한 인터페이스가 탑재되기 시작했다. \n\n 자동차로 이동할 때 필요한 주요 장치들의 제어 뿐만 아니라 네비게이션을 포함한 인포테인먼트 그리고 오디오와 함께 다양한 콘텐츠를 소비할 수 있게 발전하고 있는 엔터테인먼트까지 생성형 인공지능을 활용할 수 있는 분야는 무궁 무진하다. 이것은 단순한 가능성이 아니라 처음에는 프리미엄급의 기준이 생성형 인공지능의 탑재 여부가 될 예정이고 더 나아가 전체적인 자동차의 기능과 어떻게 잘 통합할 수 있는지 여부는 자동차 회사의 미래 가치에 치명적인 영향을 끼치게 될 것이다. \n\n 이런 면에 있어서 이미 충분한 컴퓨팅 파워를 탑재하고 있는 프리미엄급의 전기 자동차들은 생성형 인공지능의 초기 데뷔 무대가 될 확률이 높다. 지금까지 전기 자동차는 베터리와 모터와 같은 전기 장비들을 잘 통합하고 경쟁력 있는 가격에 제공하는 것이 주요 경쟁력이었다면 앞으로는 전기 계통의 플랫폼들은 모두 기본 이상의 품질을 갖추게 되고 결국 사람들이 직접 느낄 수 있는 편의성과 고급스러움이 경쟁력이 될 예정이며 여기에서 핵심 기술이 ChatGPT와 같은 LLM 기술이 될 것으로 보인다. \n\n\n\n<그림4> 자동차 산업에서의 생성형 인공지능 (출처: AI In Cars: 14 Types of Automotive AI | Built In)\n\n\n\n 자동차만 변화의 대상이 되지 않는다. 교통이란 항상 한정된 자원인 도로를 이용해서 원활한 이동을 이끌어 내기 위해서 항상 많은 데이터를 거의 실시간으로 처리하는 것이 일상이다. 이런 데이터를 기반으로 의사결정을 하고 차량의 흐름을 통제하는데 역시 생성형 인공지능이 적극적으로 활용 될 수 있다. 이미 지금도 데이터에 대해서 질문만 했을 뿐인데 그 답을 찾기 위해서 생성형 인공지능이 스스로 데이터를 분석하기 위한 코드를 작성하고 실행해서 얻어진 결과로 답변을 작성해서 알려준다. \n\n ChatGPT의 이런 발전 속도와 변화는 사실 IT업계에 종사하는 사람들 조차 받아들이기 버거울 정도로 크다. 하지만 1년이 되지 않는 이런 변화의 시작이 3년이 지났을 때 그리고 10년이 지났을 때 또 얼마나 큰 변화를 가져다 줄지는 가늠하기 어렵다. 하지만 한 가지 확실한 것은 그 변화에 전면부에 올라타는 것과 그렇지 못한 경우의 차이는 치명적일 것이라는 것 만큼은 분명할 것이다.")]
page_content='LLM이 만들어 내는 혁명과 교통산업

김영욱

Microsoft에서 플랫폼 사업부에서 수석으로 일했으며 지금은 AI 전문기업인 Hello AI 창업해서 인공지능과 관련한 프로젝트 및 과제를 수행하고 있으며 강연과 집필 그리고 교육에도 힘쓰고 있다.



 최근 모든 분야에서 이전에 없었던 급격한 기술 발전이 사회의 모습을 바꾸고 또 바뀐 사회 필요를 또 다시 새로운 기술로 채워 나가는 빠른 순환이 일어 나고 있다. 그런데 변화를 주도하는 기술 중에서 특히 IT 기술은 더더욱 그런 현상을 가속화 시킬 뿐만 아니라 주도하고 있는 현상을 우리는 쉽게 볼 수 있다.

코로나 이후 전 세계적으로 어려운 경제 상황을 보여주고 있지만 상대적으로 유럽은 더더욱 큰 경제 불황의 고리에 빠져들고 있는데 유럽 경제가 힘든 이유는 우크라이나 전쟁을 비롯, 에너지 문제를 포함해서 여러 이유를 함께 생각해 볼 수 있지만 IT산업이 제대로 발전하지 못한 이유도 크게 한 몫하고 있다. 우리가 주변에서 편하게 사용하는 다양한 인터넷 서비스들 중 유럽 것을 찾아보기 힘든 것만 봐도 유럽은 여전히 전통적인 산업에 머물러 있다는 것을 알 수 있다. 또 미국의 S&P 500의 시가 총액 상위 종목들을 보면 애플, Microsoft, 구글, 아마존 그리고 테슬라 등 IT 관련 기술주가 상위권을 휩쓸고 있는 것을 볼 수 있다. 그렇게 우리는 IT 기술이 곧 경쟁력인 세상의 한복판에 살아가고 있다.



The age of Generative AI

 작년 말 갑자기 등장한 ChatGPT는 최근 모든 이슈를 가져와도 비교가 되지 않을 만큼 큰 이슈를 일으키고 있다. 사람들은 ChatGPT를 보자마자 IT 역사에 큰 변화를 일으킬 또 하나의 마일스톤이 시작되었다는 생각 보다는 각자 필요한 용도로 활용 할 수 있다는 점에 열광하기 시작했다. 100만 사용자가 단 5일만에 가입한 사실만 보더라도 사람들이 얼마나 ChatGPT에 열광하고 있는 것을 알 수 있다.

 <그림1> 주요 서비스의 회원 100만명 달성 시간 (출처: statista)

 ChatGPT 이전에 세상에서 이슈 몰이를 했던 인공지능으로는 구글의 알파고를 빼놓고 이야기 할 수 없다. 알파고는 바둑을 혹은 바둑만 전문적으로 추론 할 수 있는 인공지능이었다. 최근 알파고 이야기를 주변에서 찾아 볼 수 없는 이유는 알파고를 바둑 이외의 영역에 적용했을 때 인상적인 결과를 만들지 못했기 때문일지도 모른다. 항상 이런 전문성이라는 것은 양날의 검과 같아서 장점과 치명적인 한계를 함께 동반하는 것이 일반적이다. 비슷하게 우리 주변의 인공지능 시스템들은 대부분은 한정된 영역의 일만 할 수 있는 소위 말하는 전문가 시스템이었다. 집안의 온도를 맞추어 주고 공장의 품질 관리를 해주고 농장의 작물들을 키워주는 인공지능 시스템들도 모두 특정 용도에 최적화된 전문가 시스템이라고 할 수 있다.

하지만 사람들이 인공지능에 거는 기대치는 이보다 훨씬 높다. 우리가 아이언맨 등의 영화에서 봤던 자비스와 같은 인공지능은 어떨까? 주인공인 토니 스타크가 묻는 질문에 적절하게 대답해주고 주변에 있는 시설들을 제어하면서 주인공의 또 하나의 동료로 완전히 함께 일하는 모습을 볼 수 있다. 사실 자비스와 같이 다양한 용도로 사용 할 수 있는 수준의 인공지능을 인공 일반 지능(AGI: Artificial General Intelligence) 기술이라고 말한다. 인공 일반 지능은 전문가 시스템에 반대되는 개념으로 사람들의 말과 말속의 맥락을 정확하게 이해하고 거기에 맞게 동작하거나 답을 해주는 것이 목표이다. ChatGPT는 이제까지 나왔던 그 어떤 인공 지능 기술 보다도 인공 일반 지능에 가장 가까운 기술이었고 그래서 사람들은 ChatGPT를 보면서 자비스를 떠올리고 있었는지도 모르겠다.



전 세계의 말들을 학습한 LLM

이전에는 컴퓨터에게 사람의 말을 가르치기 위해서 문법적인 접근을 했다. 언어들의 문법적인 원리를 연구하고 발견된 원리들을 컴퓨터에 소프트웨어로 제작하는 방식으로 접근을 했지만 의미 있는 결과를 도출하는 것이 어려웠다. 문법적인 접근이 어려움을 겪었던 이유는 모든 사람들이 문법적으로 이야기 하지 않는다는 점이 첫 번째 문제였다. 문법이라는 것이 일정한 듯 하면서도 모든 언어적인 현상들을 모두 문법으로 설명할 수 없었다. 또 다른 이유는 사람들은 계속해서 새로운 단어들을 만들어 내고 있다는 점이다. 단적인 예를 들자면 ‘구글링’이라는 단어는 구글이 등장하기 전에는 존재하지 않았던 동사였다. 그래서 문법적인 접근으로는 한계가 있음을 인정하지 않을 수 없었다. 문법적인 접근을 하는 대신 사람들이 실제 사용하는 말을 긁어 모아서 단어 사이의 가중치를 매기는 방식으로 접근하기 시작했다. 이 방식의 경우 사람들의 말의 양을 늘리면 늘릴 수록 결과물도 함께 좋아지는 장점이 있었고 또 인터넷 등에서 사람들이 실제로 사용하는 말을 모아서 학습하다 보니 새로운 단어들과 기존에 알려진 문법과 상관없는 현상들을 모두 분석할 수 있는 장점이 있었다. 문제는 말의 양을 늘리면 늘릴 수록 분석하는데 들어가는 컴퓨팅 비용도 기하급수적으로 늘어난다는 점에 있었다. 그래서 무한정으로 학습량을 늘리는 것은 어려웠다. 어찌되었든 이렇게 사람의 말을 학습해 놓은 것을 언어 모델(LM: Language Model)이라 부르는데 이 중에서도 특히 언어 모델을 엄청난 크기로 만들어 놓은 것을 거대 언어 모델(LLM: Large Language Model)이라고 불렀다.



데이터세트

토큰

교육 비율

일반 크롤링

4100억개

60%

웹텍스트 2

190억개

22%

책1

120억개

8%

책2

550억개

8%

위키백과

30억개

3%

 <표1> 대표적인 LLM인 GPT3의 학습에 사용된 데이터 양

거대 언어 모델을 만드는 데에는 엄청난 비용과 컴퓨팅 인프라가 필요한 까닭에 주요 소프트웨어 회사에서 개발하고 있다. 최근에는 주로 구글, Microsoft, 엔비디아, 그리고 오픈AI와 같은 글로벌 대형 업체들이 주도적으로 연구와 개발을 하고 있는데 이중에서도 오픈AI는 상대적으로 작은 규모의 회사이긴 하지만 Microsoft가 14조가 넘는 비용을 투자하면서 선두로 나서게 되었으며 언어 모델인 GPT, 이미지를 생성하는 DALL-E2 이외에도 많은 연구를 하고 있다.



지식전이 현상의 발견

거대 언어 모델을 만드는 과정에서 수 많은 말들을 처리하다 보니 잘 만들어진 언어 모델은 그 자체로 많은 잠재성을 가질 수 있게 되었다. 언어 모델에 들어 있는 말들 자체가 하나의 거대한 지식 체계로 동작하면서 새로운 능력들이 발현하게 되었는데 이와 같은 현상을 지식의 전이(Knowledge Transfer)라 부르게 되었다. 실제로 오픈AI가 만든 GPT-3 모델의 경우 기본적으로 감정의 분석, 문서의 요약, 번역, 질의응답, 작문, 문장의 재구성 등 많은 능력을 가지고 있어서 이미 많은 분야에서 이 능력을 활용하고 있거나 활용하기 위해서 시도하고 있다. GPT-4의 경우 이 보다 훨씬 더 큰 잠재력이 있는 것으로 알려져 있다. 지식의 전이 현상으로 인해 다양한 일들을 척척 해내는 것을 보면 거대 언어 모델의 능력이 무한 할 것 같지만 ChatGPT 역시 만능은 아니다. ChatGPT가 나름 다양한 능력을 가지고 있고 이전에 없었던 새로운 일들을 가능하게 해주는 놀라운 존재이긴 하지만 한계도 역시 분명하다. ChatGPT는 다음과 같이 알려진 한계가 있다.



2021년 9월에 멈춘 학습

일관성 없는 결과물

거짓 정보 (Hallucination)

영어에 비해 떨어지는 한국어 결과물



ChatGPT를 학습 시킬 때 전세계의 인터넷과 책에 있는 자료들을 긁어 모아서 학습을 시켰지만 그 학습 자료는 2021년 9월에 머물러 있다. 따라서 최신 정보를 묻는다면 대답을 할 수 없다. 가령 예를 들자면



‘지금 한국의 대통령은?’,

‘오늘 삼성전자 주가는 얼마야?’,

’내일 비가 올 것 같아?’



이런 질문들에 대해서는 답변을 할 수 없다. 또 ChatGPT 자체는 학습된 데이터를 기반으로 말을 생성해 내는 것이 주된 기능이고 생성된 말의 일관성이나 혹은 사실 여부를 검증해 주지는 않는다. 그래서 질문 할 때 마다 다른 말을 만들어 내주는가 하면 또 때로는 아주 아주 진지하고 그럴싸한 거짓말을 하기도 한다. 모르는 사람들은 ChatGPT가 만들어내는 거짓말을 그대로 믿을 만큼 거짓말을 잘한다. 또 다른 문제로는 GPT-4에 이르러서는 조금 나아지긴 했지만 기본적으로 한국어 보다는 영어의 학습량이 많기 때문에 한국어 보다는 영어가 더 좋은 결과물을 보여주기도 한다.



생성형 인공지능의 시대가 왔다.

위에서 ChatGPT의 한계를 이야기 했지만 업계에서는 빠르게 한계를 극복하면서 빠르게 생성형 인공지능을 제품이나 서비스로 연결하고 있다. 생성형 인공지능과 관련해서는 구글, 메타, 엔비디아 그리고 국내의 네이버 등도 빠르게 움직이고 결과물을 내놓고 있지만 최근 이 분야에서 가장 빠르게 움직이고 있는 기업은 바로 Microsoft이다.

 Microsoft는 검색엔진인 빙(Bing)에 생성형 AI 기술을 적용해서 대화형으로 문제를 해결할 수 있는 방법을 제공하면서 빠르게 구글의 점유율을 가져오고 있다. 또 빙 이미지 크리에이터를 통해서 사용자들에게 필요한 이미지를 생성 할 수 있는 방법도 함께 제공하고 있다.

 Microsoft의 전략에서 특히 눈의 띄는 부분은 바로 플랫폼이다. Microsoft는 거대 언어 모델을 그 자체로 사용하지 않고 개발을 위한 시멘틱 커널 프레임웍(Semantic Kernel Framework)을 먼저 만들고 그 기반으로 코파일럿(Copilot)라는 이름으로 플랫폼화를 했다. 플랫폼화가 잘되고 나면 안정적으로 새로운 많은 제품과 서비스에서 거대 언어 모델의 효과를 즉시 발휘할 수 있게 확장 할 수 있게 된다.

 Microsoft는 Copilot 서비스를 소프트웨어 개발 도구로 활용할 수 있게 Github Copilot으로 출시해서 소프트웨어 개발 분야에서 활용 하는가 하면 일반인들을 위해서 윈도우 11에서 거대 언어 모델을 사용할 수 있는 Windows Copilot의 오픈 베타 버전을 내놓았다.


<그림2> Windows Copilot (출처: Windows 11 Copilot 테스트 받은 편지함, ChatGPT 및 Bing AI 플러그인 통합 - GAMINGDEPUTY KOREA)

 뿐만 아니라 워드, 엑셀, 파워포인트, 팀즈, 아웃룩 등 오피스 제품들을 클라우드 기반으로 제공하는 Microsoft 365에도 역시 코파일럿 제품이 들어가면서 이제 부터는 문서 작성이나 엑셀에서 데이터 분석, 발표용 슬라이드 작성등 대부분의 작업을 이제부터는 코파일럿과의 채팅을 통해서 해결할 수 있는 시대가 왔다.

 Microsoft 뿐만 아니다. 포토샵으로 유명한 어도비(Adobe)도 적극적으로 생성형 인공지능을 활용하고 있다. 포토샵에서 여러 도구들을 사용해서 사람이 이미지를 일일이 수정하는 것이 아니라 생성형 인공지능을 사용해서 영역을 지정하고 어떻게 수정할 것인지 말로 표현하면 인공지능이 이미지를 수정해주는 식으로 동작 할 수 있다.



<그림3> 포토샵에서 생성형 인공지능의 활용(Photoshop Has Become a Lot More Powerful Thanks to Brand New Generative AI Features Using Adobe's Firefly (wccftech.com)

이렇게 생성형 인공지능 기술들은 IT 산업 전반에서 IT와 사람 사이의 인터페이스를 변화 시키고 있다. 버튼을 누르거나 사용자의 입력에 의해서 반응하던 시스템이 아니라 사람과의 대화를 통해서 내용을 이용하고 함께 작업에 동참하는 자비스가 어느덧 이제는 우리 곁으로 들어왔다.



교통산업과 거대 언어 모델

미국 최대 자동차 회사인 제너럴모터스(GM)이 ChatGPT를 자사 차량에 적용하는 방안을 모색하고 있다는 발표를 했다. 이런 변화가 자연스럽게 느껴지는 것은 자동차라는 공간이 단순한 이동 수단을 넘어서서 이제는 하나의 스마트 디바이스로 진화하고 있기 때문이다. 고성능 컴퓨터가 탑재되어서 완벽하지는 않아도 운전 보조 장치로는 충분한 수준의 자율주행을 수행할 수 있게 되었고 음성으로 대화가 가능한 인터페이스가 탑재되기 시작했다.

 자동차로 이동할 때 필요한 주요 장치들의 제어 뿐만 아니라 네비게이션을 포함한 인포테인먼트 그리고 오디오와 함께 다양한 콘텐츠를 소비할 수 있게 발전하고 있는 엔터테인먼트까지 생성형 인공지능을 활용할 수 있는 분야는 무궁 무진하다. 이것은 단순한 가능성이 아니라 처음에는 프리미엄급의 기준이 생성형 인공지능의 탑재 여부가 될 예정이고 더 나아가 전체적인 자동차의 기능과 어떻게 잘 통합할 수 있는지 여부는 자동차 회사의 미래 가치에 치명적인 영향을 끼치게 될 것이다.

 이런 면에 있어서 이미 충분한 컴퓨팅 파워를 탑재하고 있는 프리미엄급의 전기 자동차들은 생성형 인공지능의 초기 데뷔 무대가 될 확률이 높다. 지금까지 전기 자동차는 베터리와 모터와 같은 전기 장비들을 잘 통합하고 경쟁력 있는 가격에 제공하는 것이 주요 경쟁력이었다면 앞으로는 전기 계통의 플랫폼들은 모두 기본 이상의 품질을 갖추게 되고 결국 사람들이 직접 느낄 수 있는 편의성과 고급스러움이 경쟁력이 될 예정이며 여기에서 핵심 기술이 ChatGPT와 같은 LLM 기술이 될 것으로 보인다.



<그림4> 자동차 산업에서의 생성형 인공지능 (출처: AI In Cars: 14 Types of Automotive AI | Built In)



 자동차만 변화의 대상이 되지 않는다. 교통이란 항상 한정된 자원인 도로를 이용해서 원활한 이동을 이끌어 내기 위해서 항상 많은 데이터를 거의 실시간으로 처리하는 것이 일상이다. 이런 데이터를 기반으로 의사결정을 하고 차량의 흐름을 통제하는데 역시 생성형 인공지능이 적극적으로 활용 될 수 있다. 이미 지금도 데이터에 대해서 질문만 했을 뿐인데 그 답을 찾기 위해서 생성형 인공지능이 스스로 데이터를 분석하기 위한 코드를 작성하고 실행해서 얻어진 결과로 답변을 작성해서 알려준다.

 ChatGPT의 이런 발전 속도와 변화는 사실 IT업계에 종사하는 사람들 조차 받아들이기 버거울 정도로 크다. 하지만 1년이 되지 않는 이런 변화의 시작이 3년이 지났을 때 그리고 10년이 지났을 때 또 얼마나 큰 변화를 가져다 줄지는 가늠하기 어렵다. 하지만 한 가지 확실한 것은 그 변화에 전면부에 올라타는 것과 그렇지 못한 경우의 차이는 치명적일 것이라는 것 만큼은 분명할 것이다.' metadata={'source': '/content/LLM이 만들어 내는 혁명과 교통산업.docx'}

In [23]:
# CSV파일을 읽어서 Document 형태로 파싱

from langchain.document_loaders import CSVLoader

loader = CSVLoader(file_path='/content/titanic3.csv',
                   csv_args= {
                       'delimiter': ',',
                       'quotechar': '"',
                       'fieldnames': ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
                   }) #quotation charater를 "" 로 사용
data = loader.load()
print(data)
print(data[:10])

[Document(metadata={'source': '/content/titanic3.csv', 'row': 0}, page_content='PassengerId: \ufeffpclass\nSurvived: survived\nPclass: name\nName: sex\nSex: age\nAge: sibsp\nSibSp: parch\nParch: ticket\nTicket: fare\nFare: cabin\nCabin: embarked\nEmbarked: boat\nNone: body,home.dest'), Document(metadata={'source': '/content/titanic3.csv', 'row': 1}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Allen, Miss. Elisabeth Walton\nName: female\nSex: 29\nAge: 0\nSibSp: 0\nParch: 24160\nTicket: 211.3375\nFare: B5\nCabin: S\nEmbarked: 2\nNone: ,St Louis, MO'), Document(metadata={'source': '/content/titanic3.csv', 'row': 2}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Allison, Master. Hudson Trevor\nName: male\nSex: 0.9167\nAge: 1\nSibSp: 2\nParch: 113781\nTicket: 151.5500\nFare: C22 C26\nCabin: S\nEmbarked: 11\nNone: ,Montreal, PQ / Chesterville, ON'), Document(metadata={'source': '/content/titanic3.csv', 'row': 3}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Allison, Miss. Helen Loraine\nName: female\nSex: 2\nAge: 1\nSibSp: 2\nParch: 113781\nTicket: 151.5500\nFare: C22 C26\nCabin: S\nEmbarked: \nNone: ,Montreal, PQ / Chesterville, ON'), Document(metadata={'source': '/content/titanic3.csv', 'row': 4}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Allison, Mr. Hudson Joshua Creighton\nName: male\nSex: 30\nAge: 1\nSibSp: 2\nParch: 113781\nTicket: 151.5500\nFare: C22 C26\nCabin: S\nEmbarked: \nNone: 135,Montreal, PQ / Chesterville, ON'), Document(metadata={'source': '/content/titanic3.csv', 'row': 5}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Allison, Mrs. Hudson J C (Bessie Waldo Daniels)\nName: female\nSex: 25\nAge: 1\nSibSp: 2\nParch: 113781\nTicket: 151.5500\nFare: C22 C26\nCabin: S\nEmbarked: \nNone: ,Montreal, PQ / Chesterville, ON'), Document(metadata={'source': '/content/titanic3.csv', 'row': 6}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Anderson, Mr. Harry\nName: male\nSex: 48\nAge: 0\nSibSp: 0\nParch: 19952\nTicket: 26.5500\nFare: E12\nCabin: S\nEmbarked: 3\nNone: ,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 7}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Andrews, Miss. Kornelia Theodosia\nName: female\nSex: 63\nAge: 1\nSibSp: 0\nParch: 13502\nTicket: 77.9583\nFare: D7\nCabin: S\nEmbarked: 10\nNone: ,Hudson, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 8}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Andrews, Mr. Thomas Jr\nName: male\nSex: 39\nAge: 0\nSibSp: 0\nParch: 112050\nTicket: 0.0000\nFare: A36\nCabin: S\nEmbarked: \nNone: ,Belfast, NI'), Document(metadata={'source': '/content/titanic3.csv', 'row': 9}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Appleton, Mrs. Edward Dale (Charlotte Lamson)\nName: female\nSex: 53\nAge: 2\nSibSp: 0\nParch: 11769\nTicket: 51.4792\nFare: C101\nCabin: S\nEmbarked: D\nNone: ,Bayside, Queens, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 10}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Artagaveytia, Mr. Ramon\nName: male\nSex: 71\nAge: 0\nSibSp: 0\nParch: PC 17609\nTicket: 49.5042\nFare: \nCabin: C\nEmbarked: \nNone: 22,Montevideo, Uruguay'), Document(metadata={'source': '/content/titanic3.csv', 'row': 11}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Astor, Col. John Jacob\nName: male\nSex: 47\nAge: 1\nSibSp: 0\nParch: PC 17757\nTicket: 227.5250\nFare: C62 C64\nCabin: C\nEmbarked: \nNone: 124,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 12}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Astor, Mrs. John Jacob (Madeleine Talmadge Force)\nName: female\nSex: 18\nAge: 1\nSibSp: 0\nParch: PC 17757\nTicket: 227.5250\nFare: C62 C64\nCabin: C\nEmbarked: 4\nNone: ,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 13}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Aubart, Mme. Leontine Pauline\nName: female\nSex: 24\nAge: 0\nSibSp: 0\nParch: PC 17477\nTicket: 69.3000\nFare: B35\nCabin: C\nEmbarked: 9\nNone: ,Paris, France'), Document(metadata={'source': '/content/titanic3.csv', 'row': 14}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Barber, Miss. Ellen "Nellie"\nName: female\nSex: 26\nAge: 0\nSibSp: 0\nParch: 19877\nTicket: 78.8500\nFare: \nCabin: S\nEmbarked: 6\nNone: ,'), Document(metadata={'source': '/content/titanic3.csv', 'row': 15}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Barkworth, Mr. Algernon Henry Wilson\nName: male\nSex: 80\nAge: 0\nSibSp: 0\nParch: 27042\nTicket: 30.0000\nFare: A23\nCabin: S\nEmbarked: B\nNone: ,Hessle, Yorks'), Document(metadata={'source': '/content/titanic3.csv', 'row': 16}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Baumann, Mr. John D\nName: male\nSex: \nAge: 0\nSibSp: 0\nParch: PC 17318\nTicket: 25.9250\nFare: \nCabin: S\nEmbarked: \nNone: ,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 17}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Baxter, Mr. Quigg Edmond\nName: male\nSex: 24\nAge: 0\nSibSp: 1\nParch: PC 17558\nTicket: 247.5208\nFare: B58 B60\nCabin: C\nEmbarked: \nNone: ,Montreal, PQ'), Document(metadata={'source': '/content/titanic3.csv', 'row': 18}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Baxter, Mrs. James (Helene DeLaudeniere Chaput)\nName: female\nSex: 50\nAge: 0\nSibSp: 1\nParch: PC 17558\nTicket: 247.5208\nFare: B58 B60\nCabin: C\nEmbarked: 6\nNone: ,Montreal, PQ'), Document(metadata={'source': '/content/titanic3.csv', 'row': 19}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bazzani, Miss. Albina\nName: female\nSex: 32\nAge: 0\nSibSp: 0\nParch: 11813\nTicket: 76.2917\nFare: D15\nCabin: C\nEmbarked: 8\nNone: ,'), Document(metadata={'source': '/content/titanic3.csv', 'row': 20}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Beattie, Mr. Thomson\nName: male\nSex: 36\nAge: 0\nSibSp: 0\nParch: 13050\nTicket: 75.2417\nFare: C6\nCabin: C\nEmbarked: A\nNone: ,Winnipeg, MN'), Document(metadata={'source': '/content/titanic3.csv', 'row': 21}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Beckwith, Mr. Richard Leonard\nName: male\nSex: 37\nAge: 1\nSibSp: 1\nParch: 11751\nTicket: 52.5542\nFare: D35\nCabin: S\nEmbarked: 5\nNone: ,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 22}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Beckwith, Mrs. Richard Leonard (Sallie Monypeny)\nName: female\nSex: 47\nAge: 1\nSibSp: 1\nParch: 11751\nTicket: 52.5542\nFare: D35\nCabin: S\nEmbarked: 5\nNone: ,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 23}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Behr, Mr. Karl Howell\nName: male\nSex: 26\nAge: 0\nSibSp: 0\nParch: 111369\nTicket: 30.0000\nFare: C148\nCabin: C\nEmbarked: 5\nNone: ,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 24}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bidois, Miss. Rosalie\nName: female\nSex: 42\nAge: 0\nSibSp: 0\nParch: PC 17757\nTicket: 227.5250\nFare: \nCabin: C\nEmbarked: 4\nNone: ,'), Document(metadata={'source': '/content/titanic3.csv', 'row': 25}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bird, Miss. Ellen\nName: female\nSex: 29\nAge: 0\nSibSp: 0\nParch: PC 17483\nTicket: 221.7792\nFare: C97\nCabin: S\nEmbarked: 8\nNone: ,'), Document(metadata={'source': '/content/titanic3.csv', 'row': 26}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Birnbaum, Mr. Jakob\nName: male\nSex: 25\nAge: 0\nSibSp: 0\nParch: 13905\nTicket: 26.0000\nFare: \nCabin: C\nEmbarked: \nNone: 148,San Francisco, CA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 27}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bishop, Mr. Dickinson H\nName: male\nSex: 25\nAge: 1\nSibSp: 0\nParch: 11967\nTicket: 91.0792\nFare: B49\nCabin: C\nEmbarked: 7\nNone: ,Dowagiac, MI'), Document(metadata={'source': '/content/titanic3.csv', 'row': 28}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bishop, Mrs. Dickinson H (Helen Walton)\nName: female\nSex: 19\nAge: 1\nSibSp: 0\nParch: 11967\nTicket: 91.0792\nFare: B49\nCabin: C\nEmbarked: 7\nNone: ,Dowagiac, MI'), Document(metadata={'source': '/content/titanic3.csv', 'row': 29}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bissette, Miss. Amelia\nName: female\nSex: 35\nAge: 0\nSibSp: 0\nParch: PC 17760\nTicket: 135.6333\nFare: C99\nCabin: S\nEmbarked: 8\nNone: ,'), Document(metadata={'source': '/content/titanic3.csv', 'row': 30}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bjornstrom-Steffansson, Mr. Mauritz Hakan\nName: male\nSex: 28\nAge: 0\nSibSp: 0\nParch: 110564\nTicket: 26.5500\nFare: C52\nCabin: S\nEmbarked: D\nNone: ,Stockholm, Sweden / Washington, DC'), Document(metadata={'source': '/content/titanic3.csv', 'row': 31}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Blackwell, Mr. Stephen Weart\nName: male\nSex: 45\nAge: 0\nSibSp: 0\nParch: 113784\nTicket: 35.5000\nFare: T\nCabin: S\nEmbarked: \nNone: ,Trenton, NJ'), Document(metadata={'source': '/content/titanic3.csv', 'row': 32}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Blank, Mr. Henry\nName: male\nSex: 40\nAge: 0\nSibSp: 0\nParch: 112277\nTicket: 31.0000\nFare: A31\nCabin: C\nEmbarked: 7\nNone: ,Glen Ridge, NJ'), Document(metadata={'source': '/content/titanic3.csv', 'row': 33}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bonnell, Miss. Caroline\nName: female\nSex: 30\nAge: 0\nSibSp: 0\nParch: 36928\nTicket: 164.8667\nFare: C7\nCabin: S\nEmbarked: 8\nNone: ,Youngstown, OH'), Document(metadata={'source': '/content/titanic3.csv', 'row': 34}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bonnell, Miss. Elizabeth\nName: female\nSex: 58\nAge: 0\nSibSp: 0\nParch: 113783\nTicket: 26.5500\nFare: C103\nCabin: S\nEmbarked: 8\nNone: ,Birkdale, England Cleveland, Ohio'), Document(metadata={'source': '/content/titanic3.csv', 'row': 35}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Borebank, Mr. John James\nName: male\nSex: 42\nAge: 0\nSibSp: 0\nParch: 110489\nTicket: 26.5500\nFare: D22\nCabin: S\nEmbarked: \nNone: ,London / Winnipeg, MB'), Document(metadata={'source': '/content/titanic3.csv', 'row': 36}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bowen, Miss. Grace Scott\nName: female\nSex: 45\nAge: 0\nSibSp: 0\nParch: PC 17608\nTicket: 262.3750\nFare: \nCabin: C\nEmbarked: 4\nNone: ,Cooperstown, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 37}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bowerman, Miss. Elsie Edith\nName: female\nSex: 22\nAge: 0\nSibSp: 1\nParch: 113505\nTicket: 55.0000\nFare: E33\nCabin: S\nEmbarked: 6\nNone: ,St Leonards-on-Sea, England Ohio'), Document(metadata={'source': '/content/titanic3.csv', 'row': 38}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bradley, Mr. George ("George Arthur Brayton")\nName: male\nSex: \nAge: 0\nSibSp: 0\nParch: 111427\nTicket: 26.5500\nFare: \nCabin: S\nEmbarked: 9\nNone: ,Los Angeles, CA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 39}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Brady, Mr. John Bertram\nName: male\nSex: 41\nAge: 0\nSibSp: 0\nParch: 113054\nTicket: 30.5000\nFare: A21\nCabin: S\nEmbarked: \nNone: ,Pomeroy, WA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 40}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Brandeis, Mr. Emil\nName: male\nSex: 48\nAge: 0\nSibSp: 0\nParch: PC 17591\nTicket: 50.4958\nFare: B10\nCabin: C\nEmbarked: \nNone: 208,Omaha, NE'), Document(metadata={'source': '/content/titanic3.csv', 'row': 41}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Brewe, Dr. Arthur Jackson\nName: male\nSex: \nAge: 0\nSibSp: 0\nParch: 112379\nTicket: 39.6000\nFare: \nCabin: C\nEmbarked: \nNone: ,Philadelphia, PA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 42}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Brown, Mrs. James Joseph (Margaret Tobin)\nName: female\nSex: 44\nAge: 0\nSibSp: 0\nParch: PC 17610\nTicket: 27.7208\nFare: B4\nCabin: C\nEmbarked: 6\nNone: ,Denver, CO'), Document(metadata={'source': '/content/titanic3.csv', 'row': 43}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Brown, Mrs. John Murray (Caroline Lane Lamson)\nName: female\nSex: 59\nAge: 2\nSibSp: 0\nParch: 11769\nTicket: 51.4792\nFare: C101\nCabin: S\nEmbarked: D\nNone: ,Belmont, MA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 44}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Bucknell, Mrs. William Robert (Emma Eliza Ward)\nName: female\nSex: 60\nAge: 0\nSibSp: 0\nParch: 11813\nTicket: 76.2917\nFare: D15\nCabin: C\nEmbarked: 8\nNone: ,Philadelphia, PA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 45}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Burns, Miss. Elizabeth Margaret\nName: female\nSex: 41\nAge: 0\nSibSp: 0\nParch: 16966\nTicket: 134.5000\nFare: E40\nCabin: C\nEmbarked: 3\nNone: ,'), Document(metadata={'source': '/content/titanic3.csv', 'row': 46}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Butt, Major. Archibald Willingham\nName: male\nSex: 45\nAge: 0\nSibSp: 0\nParch: 113050\nTicket: 26.5500\nFare: B38\nCabin: S\nEmbarked: \nNone: ,Washington, DC'), Document(metadata={'source': '/content/titanic3.csv', 'row': 47}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Cairns, Mr. Alexander\nName: male\nSex: \nAge: 0\nSibSp: 0\nParch: 113798\nTicket: 31.0000\nFare: \nCabin: S\nEmbarked: \nNone: ,'), Document(metadata={'source': '/content/titanic3.csv', 'row': 48}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Calderhead, Mr. Edward Pennington\nName: male\nSex: 42\nAge: 0\nSibSp: 0\nParch: PC 17476\nTicket: 26.2875\nFare: E24\nCabin: S\nEmbarked: 5\nNone: ,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 49}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Candee, Mrs. Edward (Helen Churchill Hungerford)\nName: female\nSex: 53\nAge: 0\nSibSp: 0\nParch: PC 17606\nTicket: 27.4458\nFare: \nCabin: C\nEmbarked: 6\nNone: ,Washington, DC'), Document(metadata={'source': '/content/titanic3.csv', 'row': 50}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Cardeza, Mr. Thomas Drake Martinez\nName: male\nSex: 36\nAge: 0\nSibSp: 1\nParch: PC 17755\nTicket: 512.3292\nFare: B51 B53 B55\nCabin: C\nEmbarked: 3\nNone: ,Austria-Hungary / Germantown, Philadelphia, PA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 51}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)\nName: female\nSex: 58\nAge: 0\nSibSp: 1\nParch: PC 17755\nTicket: 512.3292\nFare: B51 B53 B55\nCabin: C\nEmbarked: 3\nNone: ,Germantown, Philadelphia, PA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 52}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Carlsson, Mr. Frans Olof\nName: male\nSex: 33\nAge: 0\nSibSp: 0\nParch: 695\nTicket: 5.0000\nFare: B51 B53 B55\nCabin: S\nEmbarked: \nNone: ,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 53}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Carrau, Mr. Francisco M\nName: male\nSex: 28\nAge: 0\nSibSp: 0\nParch: 113059\nTicket: 47.1000\nFare: \nCabin: S\nEmbarked: \nNone: ,Montevideo, Uruguay'), Document(metadata={'source': '/content/titanic3.csv', 'row': 54}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Carrau, Mr. Jose Pedro\nName: male\nSex: 17\nAge: 0\nSibSp: 0\nParch: 113059\nTicket: 47.1000\nFare: \nCabin: S\nEmbarked: \nNone: ,Montevideo, Uruguay'), Document(metadata={'source': '/content/titanic3.csv', 'row': 55}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Carter, Master. William Thornton II\nName: male\nSex: 11\nAge: 1\nSibSp: 2\nParch: 113760\nTicket: 120.0000\nFare: B96 B98\nCabin: S\nEmbarked: 4\nNone: ,Bryn Mawr, PA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 56}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Carter, Miss. Lucile Polk\nName: female\nSex: 14\nAge: 1\nSibSp: 2\nParch: 113760\nTicket: 120.0000\nFare: B96 B98\nCabin: S\nEmbarked: 4\nNone: ,Bryn Mawr, PA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 57}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Carter, Mr. William Ernest\nName: male\nSex: 36\nAge: 1\nSibSp: 2\nParch: 113760\nTicket: 120.0000\nFare: B96 B98\nCabin: S\nEmbarked: C\nNone: ,Bryn Mawr, PA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 58}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Carter, Mrs. William Ernest (Lucile Polk)\nName: female\nSex: 36\nAge: 1\nSibSp: 2\nParch: 113760\nTicket: 120.0000\nFare: B96 B98\nCabin: S\nEmbarked: 4\nNone: ,Bryn Mawr, PA'), Document(metadata={'source': '/content/titanic3.csv', 'row': 59}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Case, Mr. Howard Brown\nName: male\nSex: 49\nAge: 0\nSibSp: 0\nParch: 19924\nTicket: 26.0000\nFare: \nCabin: S\nEmbarked: \nNone: ,Ascot, Berkshire / Rochester, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 60}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)\nName: female\nSex: \nAge: 0\nSibSp: 0\nParch: 17770\nTicket: 27.7208\nFare: \nCabin: C\nEmbarked: 5\nNone: ,New York, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 61}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Cavendish, Mr. Tyrell William\nName: male\nSex: 36\nAge: 1\nSibSp: 0\nParch: 19877\nTicket: 78.8500\nFare: C46\nCabin: S\nEmbarked: \nNone: 172,Little Onn Hall, Staffs'), Document(metadata={'source': '/content/titanic3.csv', 'row': 62}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Cavendish, Mrs. Tyrell William (Julia Florence Siegel)\nName: female\nSex: 76\nAge: 1\nSibSp: 0\nParch: 19877\nTicket: 78.8500\nFare: C46\nCabin: S\nEmbarked: 6\nNone: ,Little Onn Hall, Staffs'), Document(metadata={'source': '/content/titanic3.csv', 'row': 63}, page_content='PassengerId: 1\nSurvived: 0\nPclass: Chaffee, Mr. Herbert Fuller\nName: male\nSex: 46\nAge: 1\nSibSp: 0\nParch: W.E.P. 5734\nTicket: 61.1750\nFare: E31\nCabin: S\nEmbarked: \nNone: ,Amenia, ND'), Document(metadata={'source': '/content/titanic3.csv', 'row': 64}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)\nName: female\nSex: 47\nAge: 1\nSibSp: 0\nParch: W.E.P. 5734\nTicket: 61.1750\nFare: E31\nCabin: S\nEmbarked: 4\nNone: ,Amenia, ND'), Document(metadata={'source': '/content/titanic3.csv', 'row': 65}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Chambers, Mr. Norman Campbell\nName: male\nSex: 27\nAge: 1\nSibSp: 0\nParch: 113806\nTicket: 53.1000\nFare: E8\nCabin: S\nEmbarked: 5\nNone: ,New York, NY / Ithaca, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 66}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Chambers, Mrs. Norman Campbell (Bertha Griggs)\nName: female\nSex: 33\nAge: 1\nSibSp: 0\nParch: 113806\nTicket: 53.1000\nFare: E8\nCabin: S\nEmbarked: 5\nNone: ,New York, NY / Ithaca, NY'), Document(metadata={'source': '/content/titanic3.csv', 'row': 67}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Chaudanson, Miss. Victorine\nName: female\nSex: 36\nAge: 0\nSibSp: 0\nParch: PC 17608\nTicket: 262.3750\nFare: B61\nCabin: C\nEmbarked: 4\nNone: ,'), Document(metadata={'source': '/content/titanic3.csv', 'row': 68}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Cherry, Miss. Gladys\nName: female\nSex: 30\nAge: 0\nSibSp: 0\nParch: 110152\nTicket: 86.5000\nFare: B77\nCabin: S\nEmbarked: 8\nNone: ,London, England'), Document(metadata={'source': '/content/titanic3.csv', 'row': 69}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Chevre, Mr. Paul Romaine\nName: male\nSex: 45\nAge: 0\nSibSp: 0\nParch: PC 17594\nTicket: 29.7000\nFare: A9\nCabin: C\nEmbarked: 7\nNone: ,Paris, France'), Document(metadata={'source': '/content/titanic3.csv', 'row': 70}, page_content='PassengerId: 1\nSurvived: 1\nPclass: Chibnall, Mrs. (Edith Martha Bowerman)\nName: female\nSex: \nAge: 0\n